"""add storygraph_details table

Revision ID: 20260126_add_sg
Revises: 58a9e03c62b9    # NOTE: In production we'd check latest, but for this env we assume it appends
Create Date: 2026-01-26 14:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20260126_add_sg'
down_revision = None  # Update this to match the actual latest revision in migrations/versions/
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('storygraph_details',
    sa.Column('abs_id', sa.String(length=255), nullable=False),
    sa.Column('storygraph_id', sa.String(length=255), nullable=True),
    sa.Column('storygraph_title', sa.String(length=500), nullable=True),
    sa.Column('storygraph_author', sa.String(length=500), nullable=True),
    sa.Column('storygraph_pages', sa.Integer(), nullable=True),
    sa.Column('storygraph_url', sa.String(length=500), nullable=True),
    sa.Column('matched_by', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['abs_id'], ['books.abs_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('abs_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('storygraph_details')
    # ### end Alembic commands ###
